### ISSUE TITLE
Can we deliver on our promise or do we need to make different ones?

### ISSUE THREAD

**Issue by notmessenger** [ember-forge/ember-forge-ui#48]
https://github.com/ember-forge/ember-forge-ui#what-is-gained-by-this promises

> If today your application is leveraging Twitter Bootstrap and tomorrow you need to leverage Materialize instead you do not need to change any of your application's code, but instead install a different companion addon (explained in later sections).

The purpose of this issue is to determine how this repo can deliver on this promise or if this functionality cannot be promised.

Let's consider list and nav components, since I have developed these related components already and it is what is prompting this evaluation.

The perspective I have been viewing the ember-forge-ui ecosystem from is that `ember-forge-ui` will provide the API and logic for the components while the companion addons, such as `ember-forge-ui-bootstrap4` will provide the DOM, CSS, and any DOM-related Javascript used to render them utilizing the CSS framework which the companion addon is associated with.  In my mind this would mean that if `ember-forge-ui` provides things that the CSS framework does not support out of the box then it is not polyfilled in the companion addon.  To me this would mean there are some "core" companion addons representing the popular frameworks, such as Twitter Bootstrap, Foundation, etc.

So for example there is an [ef-list-header](https://github.com/ember-forge/ember-forge-ui/blob/master/addon/components/ef-list-header.js) component which is used as a sub-component of the `ef-list component` in a template but for which Twitter Bootstrap has no such concept supported out of the box.  Therefore, this is not functionality presented as part of the Ember Forge UI Twitter Bootstrap 4 offerings.

There are other components as well which can be seen by comparing [ember-forge-ui's offerings](https://github.com/ember-forge/ember-forge-ui/tree/master/addon/components) with that of [ember-forge-ui-bootstrap4's](https://github.com/ember-forge/ember-forge-ui-bootstrap4/tree/master/addon/components).

Since these ember-forge-ui concepts are not presented as part of the Twitter Bootstrap 4 offerings it would then be up to a consumer to create their own companion addon, extending `ember-forge-ui-bootstrap4`, if they wanted to utilze these concepts in their application.

I had kicked around the idea of, in addition to having the `ember-forge-ui-bootstrap4` addon, creating a `ember-forge-ui-bootstrap4-polyfill` addon that would do this work I just described.  In my mind `ember-forge-ui-bootstrap4` should remain pure to what Twitter Bootstrap is capable of offering (and other addons to their respective CSS frameworks) because the addition of anything that it does not support, such as a list header or a divider, introduces our opinion into the solution rather than it being Twitter Bootstrap's.

**So the first question I have is this:** What do you think of this approach?  What alternatives can we consider?

You may have already identified the next area of question I have now that I have explained all of above.  Let's consider the [ef-list-item](https://github.com/ember-forge/ember-forge-ui/blob/master/addon/components/ef-list-item.js) component.  Its [template](https://github.com/ember-forge/ember-forge-ui-bootstrap4/blob/master/app/templates/components/ef-list-item.hbs) yields whatever is passed to it when used, so you the most flexibility, such as:

```
{{#ef-nav as |nav|}}
  {{#nav.item}}
    Item 1
  {{/nav.item}}

  {{#nav.item}}
    {{#link-to "items"}}Item 2{{/link-to}}
  {{/nav.item}}

  {{#nav.item}}
    <a href="#" {{action "something"}}>Item 3</a>
  {{/nav.item}}

  {{#nav.item}}
    <a href="">Item 4</a>
  {{/nav.item}}
{{/ef-nav}}
```

Twitter Bootstrap implements the concept of a nav component with the following HTML:

```
<nav>
  <ul class="nav">
    <li class="nav-item">
      Item 1
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/items">Item 2</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="">Item 4</a>
    </li>
  </ul>
</nav>
```

Because we are allowing `{{#nav.item}}` to be passed whatever content it wants, instead of having 4 different components to support the different types of content that could be passed to it (text, link to a route, an action, or a link to an external resource), the ember-forge-ui system has no context with which to view the passed content.  This means that it has become the responsibility of the consuming application to know that they are using Twitter Bootstrap 4 (that one's obvious) but that they must apply the `nav-link` class themselves manually, such as:

```
{{#ef-nav as |nav|}}
  {{#nav.item}}
    Item 1
  {{/nav.item}}

  {{#nav.item}}
    {{#link-to "items" class="nav-link"}}Item 2{{/link-to}}
  {{/nav.item}}

  {{#nav.item}}
    <a href="#" class="nav-link" {{action "something"}}>Item 3</a>
  {{/nav.item}}

  {{#nav.item}}
    <a href="" class="nav-link">Item 4</a>
  {{/nav.item}}
{{/ef-nav}}
```

This would certainly have to be documented somewhere, with the logical place seeming to be the "core" companion addons for each CSS framework.

To me this is not delivering on the promise made earlier of being able to swap out CSS frameworks and not having to change any application code.  Technically you would not need to swap out any application code when you make such a switch, but you would need to change up your companion addon implementation where this logic is contained.

**So.....my second question is:** given all that you now know what do you recommend?  There are no sacred cows in regards to this endeavour so anything goes.

**Comment by davewasmer** [comment]
I work well with visuals (go figure), so here's my take on the situation:

The core problem I see is that each CSS framework will have some similar and some differing concepts. Some things like the concept of a "button" will be pretty universal, while others, like a "nav group header", might be present in only some frameworks. So each one has it's own "API surface area":

![image](https://cloud.githubusercontent.com/assets/707213/17075109/b885e0bc-5046-11e6-8117-1d0b14ded26a.png)

![image](https://cloud.githubusercontent.com/assets/707213/17075110/bd6c9c60-5046-11e6-8e63-c0b7ab9fd038.png)

Since the promise of Ember Forge is the ability to swap out frameworks with no refactoring, that means that Forge must present a single, unified, unchanging interface regardless of the underlying CSS framework. The only way to do that is via the "lowest common API" (i.e. buttons, but not nav group headers):

![image](https://cloud.githubusercontent.com/assets/707213/17075131/53caafbc-5047-11e6-8750-7827ad9b36b6.png)

But that is less than ideal for 2 reasons:

1. Ember Forge users are then restricted to only using the lowest common API, leaving the strengths of the individual framework on the table.
2. As you add more frameworks, you **can only ever shrink** the lowest common denominator, which leads to a tension: support less of more frameworks, or more of fewer frameworks?

![image](https://cloud.githubusercontent.com/assets/707213/17075151/0c23e358-5048-11e6-82b6-b5a802f618d8.png)

You might be able to bend the curve a little by falling back to polyfills, but the more you do that, the more it turns into "Ember Forge Bootstrap" rather than just "Bootstrap", which again starts to detract from the promise of Forge. 

And polyfills are an "all in" proposition - you **must** either use polyfills all the time, for every framework, or never. Elective usage leaves the developer guessing as to whether that particular part of the Forge API is supported, once again defeating the whole point.

-----

I see two paths forward:

1. Try to walk the middle ground between supporting enough frameworks, while maintaining a large enough lowest common API, so that it's still useful. This weakens, but potentially doesn't kill the original promise of Ember Forge; the "swap frameworks with no refactor" becomes "swap frameworks with less refactor". You could do this two ways:
    * Implement framework specific components (i.e. `{{ef-nav-group-header}}`) that would need to be refactored when frameworks change
    * Omit framework specific concepts entirely, leaving the user to figure them out and refactor as needed
2. Take Forge a layer higher in abstraction. Don't map Forge components 1:1 to framework concepts. Instead, you have introduce higher level concepts that bundle multiple lower level CSS framework concepts (i.e `{{ef-master-detail-layout}}` rather than `{{ef-list-item}}`). This changes what Forge is about really - it's not "swappable CSS frameworks" anymore, but rather a higher level UI framework.

My gut reaction, if I put on my hypothetical user hat, is that (1) sounds like a lot of cognitive overhead for a questionable payoff. How many times over the life of an app will I change the underlying CSS framework? Versus the learning cost of understanding the Ember Forge API?

(2) is definitely interesting, but that's a whole other ballgame. Finding those higher level abstractions will not be easy. And the higher we go, the less flexible it becomes, so finding the right balance of useful but flexible will be crucial.

----

Whew. Sorry for the novel :wink:. I hope this comes across as a constructive critique, and not as bashing the idea. A unified UI library that is CSS framework agnostic and incorporates all the best practices - that would be amazing. I hope we can figure out how to get there :beers:

**Comment by notmessenger** [comment]
@davewasmer It does not come across as bashing at all.  Thanks for putting so much effort into your response!  I've had these same thoughts bouncing around in my head as well as well as have had do to exactly what you're describing when trying to comprise the "best of breed" API for each component.

The (original) idea of Ember Forge UI is an alluring one but it is becoming harder to see how we can bring it to life.  Going to have chew on this a bit, "as they say".

**Comment by notmessenger** [comment]
The promise of being able to easily swap between CSS frameworks came from our experience in developing [sl-ember-components](http://github.com/softlayer/sl-ember-components) in which devs would comment that they enjoyed the functionality of the components but unfortunately there were using CSS framework "X" and that they could not use them in their project.

So perhaps this project's offering could be to define the characteristics of UI components and then implement them in each of the major CSS frameworks we desire to support.  So for example, keeping with the previous example, we determine that content should be able to be presented in lists that can contain dividers, headers, etc.  For all of the characteristics that can be presented with existing Twitter Bootstrap 4 classes, for example, they are used.  For those that are not our own class definitions are provided, targeted against the `ef-` named classes (and/or Twitter Bootstrap's as appropriate) providing the desired outcome.  This same approach is employed with the other CSS frameworks as well.  So a developer evaluating the Ember Forge UI components and deciding they would like to use in their project can do so, with consistency, amongst the popular (and supported) CSS frameworks.

This would mean that the CSS companion add ons become more opinionated and less pure, but the API of the components was already expressing an opinion.  It also means that this project would need to maintain several CSS companion add ons for the popular CSS frameworks, though that reality was already slowing beginning to take shape before this conversation.

Thoughts @davewasmer and @juwara0 ?

**Comment by notmessenger** [comment]
After discussion with all the path that has been chosen to be taken is that `ember-forge-ui` will provide the higher-level abstractions and the functionality and API of what we feel the components should be.  Then using Twitter Bootstrap 4 as an example the `ember-forge-ui-bootstrap4` add-on will provide the Twitter Bootstrap 4's implementation of the component's capabilities, but only those that it is able to do so for out-of-the-box.  Concepts that do not exist or cannot be supported will not be included in this add-on.  For example, `ember-forge-ui` has a `ef-list-divider` component but `ember-forge-ui-bootstrap4` will not, as Twitter Bootstrap has no such concept.

The new direction to all of this though is the addition of the `ember-forge-ui-bootstrap4-polyfill` add-on (in keeping with the Twitter Bootstrap4 example).  This add-on will then fill in the difference between the offerings of `ember-forge-ui` and any deficiencies of `ember-forge-ui-bootstrap4`.  So in this example `ember-forge-ui-bootstrap4-polyfill` would style the `ef-list-divider` with the `list-group-item` class because as an `li` element in a list this is the appropriate class to apply.  The purpose of the polyfill add-ons (e.g. `ember-forge-ui-bootstrap4-polyfill`) is not to introduce new functionality or concepts into the represented CSS framework but instead to represent the `ember-forge-ui` functionality as much as it can be.  Meaning, again in this example, that a style should not be created for the `ef-list-divider` class, but rather as many Bootstrap4-specific concepts that can be applied should be.

A consumer will still only need to install 2 add ons: `ember-forge-ui` and the polyfill of their desired CSS framework.

It is expected that `ember-forge-ui` will offer more components, features, etc than any one specific polyfill is capable of supporting due to deficiencies within any one CSS framework.
