### ISSUE TITLE
If a template addon is extended the extending one is the one that should be exporting the name of the template addon in use

### ISSUE THREAD

**Issue by notmessenger** [ember-forge/ember-forge-ui#6]
see [Define config() hook](https://github.com/ember-forge/ember-forge-ui#define-config-hook)

Determine mechanism for making this happen and add appropriate documentation to README.md

Notes to use for determination:

* check on can set and override
* check if set run after in ember config

**Comment by juwara0** [comment]
Research determined that this issue is addressed by setting the `after` hook in the package.json to the template being extended this way the extended template file is run afterwards overwriting the template.

For example if the base add-on was named: templates-bootstrap and is extended by the add-on  template-bootstrap-my-organization, then in the package.json of template-bootstrap-my-organization you would set this as follows:
```
"ember-addon": {
    "configPath": "tests/dummy/config",
    "after": "templates-bootstrap",
    "before": "ember-forge-ui"
  },

The README now captures these details: https://github.com/ember-forge/ember-forge-ui/commit/c38224b3202b1c6d6f2e58210399e3af5306c096
